### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by FTI-Herbert** [1ma/JsonRpc#8]
Hi,
we eveluate this package for our projects.
One thing we have to ask, is there a plan for a php 8.1 release?

Sy Herbert

**Comment by 1ma** [comment]
Hi Sy,

happy to hear that. The library already supports and is tested [against PHP 8.1](https://github.com/1ma/JsonRpc/blob/ad794800ce7d1b7ba2b63a0870d8878f1e40f571/.github/workflows/phpunit.yml#L11) as is. Even though the PHP version constraint in the composer.json file says [`^7.3.0 || ^7.4.0 || ^8.0.0`](https://jubianchi.github.io/semver-check/#/constraint/^7.3.0%20||%20^7.4.0%20||%20~8.0.0) I made a mistake when I wrote it: `^8.0.0` actually resolves to `>=8.0.0 <9.0.0` instead of `>=8.0.0 <8.1.0`.

I'm preventively closing the issue since you should be able to install with from PHP 8.1 already.
